#!/usr/bin/env python

import sys

from rqt_pkg_hw4.my_module import PluginSostema
from rqt_gui.main import Main

plugin = 'rqt_pkg_hw4'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))